formatter: "markdown table" # this is required
version: ">= 0.18.0"
recursive:
  enabled: false
  path: ""
sections:
  hide: []
  show: []

content: |-
  ## Terraform Module cn-networking
  Module responsible for the networking CloudNova Project

  ## For local test run
  ``` 
  terraform init --backend=false && terraform test
  ``` 
  
  {{ .Header }}
  
  {{ .Requirements }}
  
  {{ .Providers }}
  {{ .Modules }}
  
  {{ .Resources }}
  
  {{ .Inputs }}
  {{ .Outputs }}
    
  {{ .Footer }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
output-values:
  enabled: false
  from: ""
sort:
  enabled: true
  by: name
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
