name: "Terraform Module Networking // Release"

on:
  workflow_run:
    workflows: [Terraform Module Networking // CI]
    types: [completed]
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: main

      - name: Render terraform docs inside the README.md
        uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c # v1.4.1
        with:
          working-dir: .
          config-file: .terraform-docs.yml
          git-commit-message: "docs(terraform): generated documentation"
          git-push: "true"

  release:
    runs-on: ubuntu-latest
    needs: docs
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: main
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22.16.0"
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 22.0.4
          ci: true
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git
        env:
          GIT_AUTHOR_NAME: "Release [Bot]"
          GIT_AUTHOR_EMAIL: "Release [Bot] <no-replay@no-replay.com>"
